### ISSUE TITLE
Create chains MASTER PLAN

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#288]
_This is kind of a super issue that will likely be split into multiple issues for the actual implementation._

# Summary

The goal is to be able to create some number of chain models (control streams and associated model objects) from a base model. The proposed syntax is something like this:

```r
mod1000 <- copy_model_from(mod102, 1000) 

# convert control stream to Bayesian manually...
# * add the priors
# * change the estimation method
# * potentially add mu-referencing
# * add individual posterior tables (not needed in NM75?)

mod1000 <- mod1000 %>% 
  create_chains_initial_estimates() %>%    # creates the .CHN file and puts path in model object
  create_chains_models()                   # actually writes out new control streams

mod1000 %>% 
  submit_model() # this could also just be piped straight through from create_chains()
```
# Additional considerations

### Single model object
Per [this comment below](https://github.com/metrumresearchgroup/rbabylon/issues/288#issuecomment-735874075) and a discussions with @timwaterhouse and @seth127 the idea is probably to have all of these functions (`create_chains_models()` etc.) return a _single_ model object that would be connected to all the chains in some way. We anticipate this making things easier for doing things like summaries later as well.

### Editing control streams programmatically
A big part of the decision to use `METHOD=CHAIN` for this was to avoid having to edit control streams programmatically. Specifically the concern is parsing and writing things like complicated `OMEGA` blocks. If there is a reliable way to do this, then maybe we reconsider that design.

# Function Details

Some implementation detail about what each function should do

### create_chains_initial_estimates()
Create a `.CHN` file (with initial estimates for each chain) and save the path to that file in the model object.
```r
create_chains_initial_estimates <- function(.mod, .num_chains, .chain_args = list(some_defaults)) {
  # * change the $EST to METHOD=CHAIN with whatever options are in .chain_args
  # * comment out all other $EST blocks
  # * submit the model locally to create .CHN file
  # * potentially clear everything _but_ .CHN file from output folder (maybe babylon.yaml? other stuff?)
  # * add chain_file: {.mod}.CHN to model object and return model object
  .mod
}
```

Note that `.chain_args` would essentially be the options that can be passed through to `METHOD=CHAIN` in NONMEM.

### create_chains_models()
Create multiple models from a parent model that has a `chain_file` attribute.
```r
create_chains_models <- function(.mod) {
  # * chain_file <- get_chain_file_path(.mod)
  # * creates new models (1000_1, 1000_2, etc. with copy_model_from) for each line in chain_file
  # * modifies new control streams:
  #   * uncomment all $EST blocks (because create_chains_initial_estimates() may have commented them out)
  #   * modify $EST METHOD=CHAIN 
  #     * delete anything there and replace with FILE={chain_file} NSAMPLE=0 ISAMPLE={.n}
  # * return list of new models
  .list_of_mods
}
```

### create_chains_custom_estimates()
This would be an optional replacement for `create_chains_intitial_estimates()` that could take any arbitrary sampling code, so that other distributions, etc. could be used. The idea is that we would define some interface for `.estimates` such that you could pass in a tibble or list of initial estimates and they would be "attached" to the model so that the model returned from this function is consistent with a model returned from `create_chains_initial_estimates()` (and could therefore be passed directly to `create_chains_models()`).
```
create_chains_custom_estimates <- (.mod, .estimates) {
  # this has to:
  # * write .estimates to {.mod}.CHN (in the right format)
  # * add chain_file: {.mod}.CHN to model object and return model object
  .mod <- .mod %>% add_chain_file("name of file")
  .mod
}
```

**Comment by timwaterhouse** [comment]
Looks great, @seth127. I like this workflow.

We'll also need to set a different seed for each chain in `create_chains_models()`, so maybe we could pass in a vector of seeds as an argument there, with a default value of `seq_len(number_of_chains)`.

**Comment by seth127** [comment]
Also, thinking about whether `create_chains_models()` should just return `mod1000` and _it_ should have the chain models attached to it (instead of returning a list of models). 

The question here @timwaterhouse @curtisKJ is whether mainly want to interact with the chain models as a unit (i.e. just interact with `mod1000`) or interact with individual chain models independently.

**Comment by callistosp** [comment]
Question about the template model that we are using here: in the above example, would model 1000 have the estimation method used for each of the chains defined, then `create_chains_initial_estimates()` **adds in** the `$EST METHOD=CHAIN` line based on the arguments you pass to the function?

I ask because if we are at some point implementing the `update_run_number` function, with this current workflow we should be careful to watch out for automatically updating *.CHN when generating the child models. Not to get too into the weeds on this, but it popped in my head as a potential pitfall

**Comment by timwaterhouse** [comment]
@callistosp I'm not sure I see the problem with `update_run_number` but yes, that was how I was thinking of it. It might make sense to strip out any existing `$EST METHOD=CHAIN` if we're going to add it to the control stream. That might head off any problems with child models.

**Comment by callistosp** [comment]
Okay cool, if `$EST METHOD=CHAIN` is generated by the function call, there shouldn't be any issue. I was thinking if it used `copy_model_from` under the hood, it might update *.CHN to the child run numbers, rather than retaining the parent run number.

**Comment by seth127** [comment]
This idea is now being implemented in the new `bbr.bayes` package: https://github.com/metrumresearchgroup/bbr.bayes/issues?q=is%3Aissue+is%3Aopen+label%3Anmbayes

(note: as of Jan 2023, when this comment was made, that repo is still private. Planning on a first release sometime in the first half of 2023)
