### ISSUE TITLE
Update all occurrences of run_id in .ctl or .mod file

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#32]
# Summary 
Currently `copy_model_from()` optionally updates the `$PROB` line to reflect the new description and run_id. @callistosp has voiced that it would be nice if it would also update all other occurrences of the run_id throughout the control stream. He has some ad-hoc code which does this:

```
  txt <- readLines(mod2) %>%
    gsub(paste0('RUN# ', runno), paste0('RUN# ', runno2), .) %>%
    gsub(paste0(runno, '.MSF'), paste0(runno2, '.MSF'), .) %>%
    gsub(paste0(runno, '.ext'), paste0(runno2, '.ext'), .) %>%
    gsub(paste0(runno, '.tab'), paste0(runno2, '.tab'), .) %>%
    gsub(paste0(runno, 'par.tab'), paste0(runno2, 'par.tab'),.)
```

We need to consider whether we want this to be in the `copy_model_from()` function, or as a helper that could be used like `mod102 <- copy_model_from(mod101, .new_model = "102", .description = "new model desc...") %>% update_mod_file()`

We also need to consider that the run_id will be in different places in the file depending on the estimation method, etc.

**Comment by callistosp** [comment]
Really the only place model number will come up is in $PROB, $EST, and $TABLE. What if we just did a selective search for the run number within these blocks of the control stream? This would prevent off-target changes in the initial conditions and priors, which is why I did the manual change in my previous code.

Also need to take into account the different spelling options for each block, e.g. $PROB, $PROBLEM, etc.

**Comment by callistosp** [comment]
Has there been any movement on this? I think it would be some nice low-hanging fruit to add to the next release that would really improve usability during model development

**Comment by kylebaron** [comment]
Agree; if we continue to be expecting the run number to show up in the table file names and msfo file, this would be really helpful.  Using rbabylon on my project for the past several weeks, I frequently forget to update run numbers. 

**NB** there is no requirement that the table file name contains the run number; we could use run-agnostic table file names and get around this.  But I feel like people want the run number there and it would be very helpful if rbabylon could do this.

**Comment by kyleam** [comment]
As far as I can tell, this functionality is covered by `update_model_id` added in gh-417 (which is part of the 1.2.0 release), so I'll close this.  Please reopen if I'm mistaken.
