### ISSUE TITLE
tags_diff function

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#325]
# Summary

As a user, I would like to be able to easily see the difference in the `tags` element of different models. I would like to be able to either compare two models directly, or compare all models in a `bbi_run_log_df` to their  "parent models" (a.k.a. the models in that same tibble that match their `based_on`).

# Tests
- tests/testthat/test-tags-diff.R
  - tags_diff.bbi_model default happy path works
  - tags_diff.bbi_model print works
  - tags_diff.bbi_model .mod2 works
  - tags_diff.bbi_run_log_df works

**Comment by seth127** [comment]
Here's a prototype from the example project for the first use case (comparing two model directly)

```r
#' Helper to show the diff between tags
#' 
#' @param model_A `bbi_{.model_type}_model` object to compare
#' @param model_B `bbi_{.model_type}_model` object to compare
#' @param .print If `TRUE`, the default, will print to console. 
#' @return A named list with an element for both models containing
#'   the tags that are in that model but _not_ the other model. 
#'   Returns invisibly since `.print` is `TRUE` by default.
tags_diff <- function(model_A, model_B, .print = TRUE) {
  diff_A <- setdiff(model_A$tags, model_B$tags)
  diff_B <- setdiff(model_B$tags, model_A$tags)
  
  id_A <- get_model_id(model_A)
  id_B <- get_model_id(model_B)
  
  if (isTRUE(.print)) {
    cat(paste(
      glue::glue("In {id_A} but not {id_B}:\t{paste(diff_A, collapse = ', ')}\n"),
      glue::glue("In {id_B} but not {id_A}:\t{paste(diff_B, collapse = ', ')}\n"),
      sep = "\n"
    ))
  }
  
  .out <- list()
  .out[[id_A]] <- diff_A
  .out[[id_B]] <- diff_B
  
  invisible(.out)
}
```

**Comment by seth127** [comment]
And here's a prototype for the `run_log()` use case, from collabo by me and @callistosp 

```r
#' Create a tags diff column
#' 
#' **Intended to be used inside mutate.** This will 
#' return a list (that can be passed to a new column)
#' containing one element per row, each element containing
#' only the tags that are present in that row but _not_
#' in any of the "parent rows." The parent rows are the
#' rows where the `run` column matches this row's 
#' `based_on` column.
#' @importFrom purrr map map2
#'
#' @param .r The `run` column of a `bbi_log_df` tibble
#' @param .b The `based_on` column of a `bbi_log_df` tibble
#' @param .t The `tags` column of a `bbi_log_df` tibble
tags_diff_log_df <- function(.r, .b, .t) {

  parent_indices <- purrr::map(.b, ~which(.r %in% .x))
  
  parent_tags <- purrr::map(parent_indices, function(.pi) {
    if (length(.pi) == 0) {
      return(NA_character_)
    }
    
    # could have multiple parents so we map over each one 
    # and take the unique set of all of their tags
    purrr::map(.pi, ~ .t[[.x]]) %>%
      unlist() %>%
      unique()
  })
  
  purrr::map2(.t, parent_tags, ~setdiff(.x, .y))
}
```

It gets called like so
```r
log_df <- log_df %>%
  mutate(
    lag_tags = tags_diff_log_df(run, based_on, tags)
  )
````

Although if we implement this, we should probably just do the `mutate` under the hood, so you would just pass through the tibble like `log_df <- tags_diff(log_df)` to create the new column. Something like that.

**Comment by seth127** [comment]
Not sure if these could be different dispatches for a common `tags_diff` S3 method, but I like that idea. Feels like it would be a nice interface.

Also, we should consider if there are useful analogous functions for things like `notes` or `bbi_args` but I kinda doubt it.

**Comment by seth127** [comment]
@callistosp was also talking about the idea to have something for the `log_df` dispatch that could (maybe call this under the hood to) create a formatted string with all the tags (as `collapse_to_string()` does) but have tags that are _not_ in the parent model bolded and tags that in the parent but removed from the child struckthrough. Or maybe just a `tags_diff` column with only the new and removed tags, with removed tags struckthrough. This needs more thought, but it could be very cool and very informative for a quick look at what changed throughout the development process.

**Comment by seth127** [comment]
# Spec

### bbi_model object(s)

**Input:** two model objects

**Output:** list of 2 elements, first is "in A but not in B" and second is "in B but not in A"

### bbi_run_log_df

**Input:** a `bbi_run_log_df` 

**Output:** the same df, but with two new columns. For each row (model):

* "in this model but _not_ in `based_on` model(s)"
* "in `based_on` model(s) but _not_ in this model"

**Comment by seth127** [comment]
Some debate about what to do with the `log_df` "is `based_on` but _not_ in this model" when there are multiple `based_on` models.

### option 1: dedupe and concat to a single vector

<img width="463" alt="Screen Shot 2021-02-25 at 2 30 25 PM" src="https://user-images.githubusercontent.com/7806083/109206956-866bf380-7776-11eb-8732-736a6232cea6.png">

### Option 2: create a named list for each `based_on` model

<img width="471" alt="Screen Shot 2021-02-25 at 2 32 36 PM" src="https://user-images.githubusercontent.com/7806083/109207006-997ec380-7776-11eb-9ba0-6ac1c19665c4.png">

I'm strongly leaning towards option 1 for simplicity sake (and stable return value) but open to thoughts on this.

**Comment by seth127** [comment]
Alright, this is the new working prototype for the `log_df` dispatch

```r
tags_diff_log_df <- function(.df) {
  #####
  #' returns the tags in .b that aren't in .a
  #' might just refactor this to use real tags_diff...
  tags_diff_mutater <- function(.a, .b, .t) {
    parent_indices <- purrr::map(.b, ~which(.a %in% .x))
    
    parent_tags <- purrr::map(parent_indices, function(.pi) {
      if (length(.pi) == 0) {
        return("")
      }
      
      # could have multiple parents so we map over each one 
      # and take the unique set of all of their tags
      purrr::map(.pi, ~ .t[[.x]]) %>%
        unlist() %>%
        unique()
    })
    
    purrr::map2(.t, parent_tags, function(.x, .y) {
      list(
        setdiff(.x, .y),
        setdiff(.y, .x)
      )
    })
    
  }
  ####
  
  .df %>%
    mutate(
      tags_diff = tags_diff_mutater(run, based_on, tags)
    ) %>% 
    unnest(tags_diff) %>% 
    mutate(bn = rep(c("tags_added", "tags_removed"), nrow(.df))) %>% # create the names column
    pivot_wider(names_from = bn, values_from = tags_diff) %>%
    replace_na(list(tags_added = "", tags_removed = ""))
}
```

**Comment by seth127** [comment]
I decided to make the `log_df` method return a list of lists (aka [just map over tags_diff.bbi_model()](https://github.com/metrumresearchgroup/bbr/blob/feat/tags_diff/R/tags-diff.R#L102)). Primarily this just seemed much better in terms of the "consistent return value" principle.

But then I _also_ added an [add_tags_diff() function](https://github.com/metrumresearchgroup/bbr/blob/feat/tags_diff/R/tags-diff.R#L115) which adds the columns to the `log_df`. This also felt better because we already have `add_summary()` and `add_config()` which do a similar thing (return the input tibble with some new columns joined onto it).

Now you can do things like
```r
log_df <- run_log(MODEL_DIR) %>%
  add_tags_diff() %>%
  add_summary() %>%
  add_config()
```

**Comment by callistosp** [comment]
good, I like the use of consistent verbs to denote similar tasks. great idea @seth127
