### ISSUE TITLE
Add heuristics descriptions to model_summary docs

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#326]
# Summary

As a user, I would like to have detailed information in the `model_summary()` documentation about what the heuristics returned actually mean and when they are triggered.

# Tests
- no tests because this a documentation change

**Comment by seth127** [comment]
Some initial info from @anarpkpd 

> If you get a PRDERR file that  indicates that nonmem
 is unable to compute a prediction for a given data record with the current values of
theta’s and etas

> Significant ETABAR alerts you about large deviations from zero, which is one of the assumptions of the statistical model ( eta has a mean of zero with a variance of omega). It could be consequence of asymmetric shrinkage or it could be misfit

> HIgh condition number could refer to parameters highly correlated or  overparameterization  among other things.

> A gradient zero at the initial iterations indicate that there is no enough information for nonmem to estimate the parameter. Gradients can provide information about which parameters is having estimation problems, gradients should get smaller as the search progresses.

> Reset Hessian: Its appearance suggests that the search is not going easily, and perhaps (not necessarily) something is wrong. A reset indicates some problem during the search. (It indicates that the approximation to the Hessian is no longer acceptable, and must be “recomputed”.) The message can be safely ignored, unless more than just a couple of resets occur, or resets occur right before the end of the search, in which case a poor fit (judged by other means) can result, and the user should carefully regard his set-up, and consider possible reasons for why a minimum, let alone one which corresponds to a good estimate, was difficult to find (there can be many possible reasons).

**Comment by seth127** [comment]
Also, there are some descriptions in currently in `summary_log()` docs. Those should be moved to `model_summary()` and both `?summary_log` and `?model_summaries` should explicitly link to `?model_summary` for info about heuristics.

**Comment by anarpkpd** [comment]
Additional info for the heuristics:
Hessian reset:
![image](https://user-images.githubusercontent.com/68296729/110001946-bc0a6280-7cc9-11eb-904e-6359c7969ec3.png)

Minimization terminated: 
![image](https://user-images.githubusercontent.com/68296729/110002042-d5abaa00-7cc9-11eb-8465-8b7ba38dab51.png)

Param near the boundary

![image](https://user-images.githubusercontent.com/68296729/110002089-e1976c00-7cc9-11eb-912d-2771c77813c3.png)


Cov step aborted

![image](https://user-images.githubusercontent.com/68296729/110002123-eb20d400-7cc9-11eb-8515-971afff581ef.png)


Zero gradient

![image](https://user-images.githubusercontent.com/68296729/110002160-f411a580-7cc9-11eb-829f-b8b3000257eb.png)
