### ISSUE TITLE
Nested models in config log error

### ISSUE THREAD

**Issue by callistosp** [metrumresearchgroup/bbr#347]
I am running a NONMEM model that uses METHOD=CHAIN to generate a set of initial estimates for a series of nested METHOD=BAYES runs. While running `add_config()` I get the following error:

```
Error in dev_error(glue("read_model_from_config() checked {potential_nm_path} and {potential_stan_path} and the following exist: {paste(winner, collapse = ', ')}")) : 
  read_model_from_config() checked ./model/138/138_1.yaml and ./model/138.yaml and the following exist: ./model/138/138_1.yaml, ./model/138.yaml
USER SHOULD NEVER SEE THIS ERROR. If encountered, please file an issue at https://github.com/metrumresearchgroup/bbr/issues
In addition: Warning message:
In find_models(.base_dir, .recurse) :
 
 Error in dev_error(glue("read_model_from_config() checked {potential_nm_path} and {potential_stan_path} and the following exist: {paste(winner, collapse = ', ')}")) : 
  read_model_from_config() checked ./model/138/138_1.yaml and ./model/138.yaml and the following exist: ./model/138/138_1.yaml, ./model/138.yaml
USER SHOULD NEVER SEE THIS ERROR. If encountered, please file an issue at https://github.com/metrumresearchgroup/bbr/issues 
```

**Comment by seth127** [comment]
This is definitely a bug, but we're not entirely supporting the NONMEM Bayes stuff yet so I'm not surprised that weird stuff like this is happening. I put it on our NONMEM Bayes milestone so that we'll get to it once we dive into that.

For now, is it possible to use `.recurse = FALSE` to get around this? Maybe not, I'm not totally clear on what you're trying to do with this `config_log()`.

**Comment by callistosp** [comment]
I can get the log to output when I add `recurse=FALSE` so I'll just wait on the Bayes implementation for this to be fixed. Thanks @seth127

**Comment by callistosp** [comment]
bump

**Comment by callistosp** [comment]
bump @seth127

**Comment by callistosp** [comment]
related to this, in the config log the `estimation_method` column is `NULL` for all models using `$METHOD=CHAIN`

**Comment by seth127** [comment]
This idea is now being implemented in the new `bbr.bayes` package: https://github.com/metrumresearchgroup/bbr.bayes/issues?q=is%3Aissue+is%3Aopen+label%3Anmbayes

(note: as of Jan 2023, when this comment was made, that repo is still private. Planning on a first release sometime in the first half of 2023)
