### ISSUE TITLE
parallel vs threads warning

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#385]
There is an annoying situation where a user specifies more threads (e.g. through `.bbi_args(list(threads = 6))`) but forgets to add `parallel = TRUE` and therefore only one thread is used. This is especially common because `parallel` defaults to `false` in the `bbi.yaml` file.

I think we should either give a warning when `threads > 1 && parallel == FALSE`, or set `parallel: true` as the default going forward, or maybe both.

**Comment by barrettk** [comment]
What about something simple like `if(threads > 1){parallel = TRUE}`

**Comment by seth127** [comment]
Per discussions offline, related to

> I think we should either give a warning when threads > 1 && parallel == FALSE, or set parallel: true as the default going forward, or maybe both.

The plan is to make _no_ changes to `bbi`, and make the following the changes to `bbr`, in the internal `check_bbi_args()` helper:

* when `threads > 1` and `parallel` is _not_ passed, set `parallel = TRUE`
* when `parallel` is passed, don't modify the args
* when `threads > 1` and `parallel = FALSE`, warn the user that `threads > 1` but model will not run in parallel because `parallel = FALSE`

# Other changes

* modify docstrings to describe new behavior
* change https://github.com/metrumresearchgroup/bbr/blob/main/tests/testthat/test-workflow-bbi.R#L58 to `threads = 1` so that those tests still work.
