### ISSUE TITLE
handling lists in add_tags function

### ISSUE THREAD

**Issue by callistosp** [metrumresearchgroup/bbr#387]
# Summary

As a user, I want to be able to pass a list or a vector to `add_tags()` and have the correctly formatted tags persisted to the model.

# Tests
- test/testthat/test-tags.R
  - some test (this will break mrgvalidate because this test doesn't exist)

**Comment by seth127** [comment]
# Original Post

# Problem
When adding tags as a list instead of a character vector the `collapse_to_string` function doesn't work properly

## example code
```
> mod %<>% add_tags(list(TAGS$bio, TAGS$one_compartment_absorption))
> run_log(MODEL_DIR) %>% collapse_to_string(tags) %>% select(run, tags)
# A tibble: 5 x 2
  run   tags                                                                                                                      
  <chr> <chr>                                                                                                                     
1 100   "one-compartment + absorption, additive RUV, ETA-CL, ETA-KA, ETA-V"                                                       
2 101   "two-compartment + absorption, additive RUV, ETA-CL, ETA-KA, ETA-V2, CLWT-allo, V2WT-allo, V3WT-allo, QWT-allo"           
3 102   "list(\"one-compartment + absorption\", \"additive RUV\", \"ETA-CL\",     \"ETA-KA\", \"ETA-V\", \"CLWT-allo\", NULL)" 
```

# Proposed Solution
`unlist` all inputs to `add_tags` (and potentially other `add_*` functions which may be affected) when received.
