### ISSUE TITLE
test_threads()

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#397]
Helper for testing a model with different numbers of threads.

* `test_threads()` to copy and submit the models
* `check_threads()` to check the elapsed time

# Discussion points

* consider whether we could go into control stream and change `NITER` or `MAXEVAL` to a small number, probably optionally (arg defaults to NULL).

# Proposed code

```r
#' Takes a model object and runs it with various threads values
#' 
#' Returns a list of the model objects for the copied models.
#' @param .mod bbi_model object to copy/test
#' @param thread_opts Integer vector of threads values to test
#' @param .mode Passed through to bbr::submit_models(.mode)
test_threads <- function(.mod, threads_opts, .mode = "sge") {
  mods <- map(threads_opts, ~ {
    .m <- copy_model_from(
      .mod, 
      glue("{get_model_id(.mod)}_{.x}threads")
    ) %>%
      add_bbi_args(list(parallel = TRUE, threads = .x))
  })

  submit_models(mods, .mode = .mode, .wait = FALSE)

  mods
}

#' Check estimation time for models run with various threads values
#'
#' @param mods list of bbi model objects created by `test_threads()`
#' @param n_orig number of iterations needed for the original model
#' @param n_test number of iterations in the test models
#'
#' @return A tibble with columns `threads` (number of threads), `time` (elapsed
#'   estimation time in seconds for test models), and `time_orig` (predicted
#'   estimation time in minutes needed to run the original model).
#'   
#' @example 
#'   check_threads(mods, n_orig = 1000, n_test = 100)
check_threads <- function(mods, n_orig, n_test) {
  map_dfr(mods, ~ {
    s <- .x %>% model_summary()
    threads <- as.numeric(str_extract(s$absolute_model_path, "\\d+(?=threads$)"))
    tibble(threads = threads, time = s$run_details$estimation_time)
  }) %>% 
    mutate(time_orig = time * n_orig / n_test / 60)
}

```

**Comment by timwaterhouse** [comment]
The `check_threads()` function that I dropped in here assumes that the original model will run with a fixed and known number of iterations (IMP or BAYES etc). Perhaps the default (e.g. for FOCE) could be to use `n_orig` & `n_test` set to NULL and just report the estimation times without doing that last calculation.

**Comment by seth127** [comment]
note: this is mentioned in the [parallel tips and tricks vignette](https://metrumresearchgroup.github.io/bbr/articles/nonmem-parallel.html). We should update the call the new function, when this is done.

**Comment by seth127** [comment]
This was completed and released in https://github.com/metrumresearchgroup/bbr/releases/tag/1.4.0 but never got closed.
