### ISSUE TITLE
edit_model()

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#398]
Opens control stream in Rstudio GUI with `file.edit()`

# Discussions points

* might want to look into what `file.edit()` does when you're _not_ in an interactive Rstudio session (i.e. in the terminal or in an Rmd that gets knit)
* look at [comment below](https://github.com/metrumresearchgroup/bbr/issues/398#issuecomment-926668621) about other similar helpers.

# Proposed code

```r
#' Helper to open control stream for editing in Rstudio
#' @param .mod a `bb{.model_type}_model` object
edit_model <- function(.mod){
  get_model_path(.mod) %>% 
    file.edit()
}
```

**Comment by seth127** [comment]
Consider adding `edit_` (or possibly `view_`) helpers (all using `file.edit()` for other files too:

```r
view_output_file <- function(.mod, .extension){
  ## grab file with .extension
  tmpdir <- get_output_dir(.mod)
  tmpfile <- list.files(tmpdir, pattern=regex(.extension, ignore_case = TRUE))
  
  ## return NULL if file doesn't exist
  if(length(tmpfile) == 0){
    warning("File does not exist")
    return(NULL)
  }
  
  ## open file
  file.edit(file.path(tmpdir,tmpfile))
}

view_lst <- function(.mod){
  view_output_file(.mod, .extension="lst")
}
```

**Comment by kyleam** [comment]
We've added various helpers to bbr.bayes for Stan-related files, including the model file.  Notably, there's a file.edit kludge to make it work better with RStudio server.

So, if we add the proposed function

 * we should absorb the file.edit kludge from bbr.bayes
 * adjust bbr.bayes to 1) remove the kludge and 2) make its "open model" helper an alias or wrapper around bbr's function

**Comment by seth127** [comment]
I like this idea @kyleam . We should also settle on naming for all of these... I think the `open_*` convention from the `bbr.bayes` is my current favorite.
