### ISSUE TITLE
friendlier tail_output() when run completed

### ISSUE THREAD

**Issue by callistosp** [metrumresearchgroup/bbr#408]
# Problem

Currently, if you call `tail_output()` when a NONMEM model has finished running, it simply says that the file is not found. It would be more easily interpreted if we could catch that error and just tell the user that the model has finished running.

**Comment by seth127** [comment]
This is a good idea. If you or @barrettk wants to knock this out sometime, you are welcome to it. Either way, we'll put it on the docket for the next release.
