### ISSUE TITLE
return omega/sigma matrix from model_summary object

### ISSUE THREAD

**Issue by callistosp** [metrumresearchgroup/bbr#442]
## Problem:
As a user, I want to easily access the OMEGA matrix for a given model run. Currently the OMEGA half-matrix stored in the `model_summary` object is accessible through `modsum$parameters_data[[1]]$estimates$omega`. It would be more useful if we had a helper function that could easily return the full matrix. This would entail filling the top half the half-matrix currently in the vector and returning a `matrix` object.

**Comment by seth127** [comment]
Should we have a similar helper for the SIGMA matrix?

Also, I assume you can get whatever you need related to THETA from either `param_estimates()` or `param_estimates_batch()`, but let us know if that's _not_ correct.

**Comment by kylebaron** [comment]
THETA is not simple to get from `param_estimates()` (it's possible but not simple). If you have additional helpers to go get everything, it would be 5 functions that need to get called in order to extract this basic information. 

How about a single function call to get the estimates back from a given estimation method:

```r
> x$parameters_data[[1]]$estimates
$theta
[1]  0.4431030  4.1189900  1.1719500  4.2094100  1.2845500  0.4847440 -0.0377712  0.4189300

$omega
[1] 0.2187490 0.0668106 0.0823777 0.1214010 0.0703631 0.1144050

$sigma
[1] 0.0399375
```

`theta` has names and `omega` and `sigma` are matrices; matrices could have names but IMO less likely to need them.

**Comment by callistosp** [comment]
I like the idea of getting theta, omega, and sigma all as a list from one function call, but I think a function that just returns the omega or sigma matrix would be nice too.

**Comment by callistosp** [comment]
Thanks for the work on this guys! 

My initial thought is that the separate `get_*()` implementation should work fine. If someone wants a function which returns everything they could build a helper similar to what you describe, but I think the base case will be that people will just want to pull in one or two which will then be used separately (@kylebaron would love your opinion on this as well).

The reason why I have wanted to use something like this is to pull in the final estimates for some simulations. In this case I would also want to just pull in the estimates from the final estimation method step, so I agree that it would make sense to mirror the `param_estimates()` assumption of pulling in final estimates only.

**Comment by barrettk** [comment]
Awesome thanks for the feedback so quickly! I will move forward with that assumption for now, but yes @kylebaron if you have any additional thoughts feel free to chime in

**Comment by callistosp** [comment]
I think these look great, exactly the structure that I would hope to see for the outputs. I like the implementation for multiple models as well, that will be useful.
