### ISSUE TITLE
test_threads() helper

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#472]
# Summary

Helper function to run (a short version of) a model several times with different numbers of threads, time each run, and report the results.

Basically we want to implement a version of what's shown in this vignette: https://metrumresearchgroup.github.io/bbr/articles/nonmem-parallel.html#testing-different-numbers-of-threads

# Specification

## Arguments

- `test_threads()`
  - model
  - threads
  - iterations
    - "cap the iterations to 10 or 20 by changing MAX_EVAL or NITER in your control stream"
  - .bbi_args
- `check_threads()`
  - a list of models
 
## Return values
- `test_threads()` returns the list of models
- `check_threads()` returns tibble of times for the models that have finished (with `NA` for the models that haven't)

## Error handling
- `check_threads()` should warn and continue if some of the models can't be parsed

**Comment by barrettk** [comment]
Stories and requirements can be found [here](https://github.com/metrumresearchgroup/bbr/issues/488#issuecomment-1145358906)
