### ISSUE TITLE
use_bbi() create destination directory

### ISSUE THREAD

**Issue by graceannobrien** [metrumresearchgroup/bbr#483]
When I call use_bbi() to install bbi, I would like it to create the destination directory if it doesn't already exist.

**Comment by seth127** [comment]
@kyleam any thoughts on this? It would be more convenient (and `use_bbi()` is certainly a "convenience function") but I want to be sure there aren't any downsides that I haven't thought of.

**Comment by kyleam** [comment]
I can't think of any downsides.
