### ISSUE TITLE
nm_join with .superset = TRUE is not sorted properly

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/bbr#490]
# Summary

calling 

```r
data <- nm_join(mod, .superset = TRUE)
```
should return a data frame with 

1. the same number of rows as the entire input data set (no ignores) and
2. in the same row order as the original input data set

I believe that the joins are happening in such a way that the sort order is off.

**Comment by barrettk** [comment]
Hey @kylebaron do you have any reproducible examples of the sort order being off? Im not seeing any examples of incorrect sorting via bbr's example model or the ones from the example project I tested. Mainly trying to decide whether this issue deserves any new tests/requirements.

snippet:
![image](https://user-images.githubusercontent.com/18685116/173137209-ac56d4f4-82ce-4906-9e1b-51e4ef60c3a1.png)

**Comment by kylebaron** [comment]
Hi @barrettk  - 

I can't make a reprex (?) on Metworx; but I saw this on a project model

```
> d <- nm_data(read_model(here("model/nonmem/201")))
Reading data file: xyz-pk-da-2.csv
  rows: 7808
  cols: 52

> x <- nm_join(here("model/nonmem/201"), .superset=TRUE)
Reading data file: xyz-pk-da-2.csv                                                                                   
  rows: 7808
  cols: 52

Reading 201.tab
  rows: 3989
  cols: 11

tab adds 10 new cols                                                                                                      

final join stats:
  rows: 7808
  cols: 62
> 
> plot(x$NUM, d$NUM)
> summary(x$NUM - d$NUM)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  -3989   -1976      28       0    1987    3819 
> 
> sorted <- arrange(x, NUM)
> plot(sorted$NUM, d$NUM)
> summary(sorted$NUM - d$NUM)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      0       0       0       0       0       0 
```

**Comment by kylebaron** [comment]
I'm getting the same thing in the Example Project

```r
d <- nm_data(read_model(here("model/pk/106")))
x <- nm_join(here("model/pk/106"), .superset = TRUE)
plot(x$NUM)
plot(d$NUM)
```
<img width="629" alt="Screen Shot 2022-06-17 at 11 58 15 PM" src="https://user-images.githubusercontent.com/16908301/174423467-6357af7d-8926-4adb-8829-d8cae2ba806e.png">
<img width="625" alt="Screen Shot 2022-06-17 at 11 58 22 PM" src="https://user-images.githubusercontent.com/16908301/174423476-dde98543-6435-432f-9697-c14c0f82f9c5.png">

**Comment by barrettk** [comment]
@kylebaron 

Still investigating this but I wasn't able to reproduce your error so far. Using the same model (106 from the example project):

```r
MODEL_DIR <- system.file("model", "nonmem", "basic",   package = "bbr")

mod106 <- read_model(file.path(MODEL_DIR, "106"))


data_reg <- nm_join(mod106)

data_super <- nm_join(mod106, .superset = TRUE)

plot(data_reg$NUM, data_reg$NUM)

plot(data_super$NUM, data_super$NUM)
```
![image](https://user-images.githubusercontent.com/18685116/176036249-12b56854-46b7-47c1-9321-fb9c7db5851e.png)
![image](https://user-images.githubusercontent.com/18685116/176036268-8721e434-1d8a-4658-8bfc-5b15f8f0e451.png)

**Comment by kylebaron** [comment]
Hi @barrettk  -

I'd expect the plots to look like that when you plot for example `plot(data_reg$NUM, data_reg$NUM)`

In my code, I showed that NUM was strictly increasing in the data but not in the nm_join result with superset = TRUE. If superset = TRUE works right, num should be identical to what we find in the data. 

Here's some code in the example project that shows this. 

https://ghe.metrumrg.com/example-projects/bbr-nonmem-poppk-foce/pull/236

Kyle

**Comment by barrettk** [comment]
Hi @kylebaron 

Thanks for clarifying, I missed that nuance. I believe I fixed it in my last commit. Will let you know when its merged
