### ISSUE TITLE
change model_diff() output when files are identical

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#516]
Currently, when the files `model_diff()` is comparing are identical, it prints out a message saying there are identical and then prints out the entire contents of the files. This is because this is the behavior of the `diffobj::diffFile()` function that we use under the hood, but I find it to be confusing and annoying. 

Consider changing this to catch these cases and _not_ print out the entire file contents (instead printing only the message).

**Comment by seth127** [comment]
@kyleam I think we wanna knock this out before we split off `bbr.bayes` (or whatever we call it). I think we're gonna use this function a lot for Stan stuff and this the way it is now is gonna be super annoying for that stuff.

Thoughts on whether we should try to squeeze it into `1.4.0` release? It's likely a pretty small change, so I'm tempted to say "yes". The bigger issue though is how you're going to do the split for the new package. I'm not sure where you are in figuring out how you want to approach that though.

**Comment by kyleam** [comment]
> Thoughts on whether we should try to squeeze it into 1.4.0 release? It's likely a pretty small change, so I'm tempted to say "yes".

Sounds good.  PR here: gh-522

I think the touched code will remain on bbr's side, so I don't think it should come into play with the split.  (I've started to play around with tweaking and pruning the split off package, but don't have anything functional yet or a good idea of what pain points we'll hit.)

**Comment by seth127** [comment]
Like a pro, he just knocks it out. Thanks @kyleam, I'll pull that branch and test it out later just to be thorough but from a glancing at the code, it seems to be... pretty straightforward.
