### ISSUE TITLE
check_run_times: handle BBI_NULL_NUM special case?

### ISSUE THREAD

**Issue by kyleam** [metrumresearchgroup/bbr#518]
It's possible for the value of the `postprocess_time` or `cpu_time` field to come through as `BBI_NULL_NUM` if no values are parsed from the model output.  Should `check_run_times` catch this special case and convert it into something a little more obvious to the user (perhaps `NA_real_`)?

https://github.com/metrumresearchgroup/bbr/blob/f31d080e8e5fba97956fe0b1d4b8a69f1f8ec22d/R/test-threads.R#L212-L213

cc: @barrettk

**Comment by barrettk** [comment]
tbh im not sure what's desired. I would vote to get a scientists opinion on this. 

@kylebaron, @callistosp do you guys have any thoughts?

For reference:
```r
> BBI_NULL_NUM
[1] -1e+09
```

**Comment by barrettk** [comment]
@kyleam btw im not able to load that link you attached:
![image](https://user-images.githubusercontent.com/18685116/179032103-c49d4c65-0023-4563-a047-a11b0adb6784.png)

**Comment by kyleam** [comment]
> @kyleam btw im not able to load that link you attached:

Ah, thanks. That was derived from an unpushed commit.  Updated to be based off `main`.

**Comment by kyleam** [comment]
https://github.com/metrumresearchgroup/bbr/issues/520 proposes doing this replacement tree-wide
