### ISSUE TITLE
Printing of duplicate rows in nm_join is excessive

### ISSUE THREAD

**Issue by barrettk** [metrumresearchgroup/bbr#536]
After merging https://github.com/metrumresearchgroup/bbr/pull/533, @kylebaron pointed out that printing the duplicate rows could be a bit excessive in the case of 1000's of duplicates:
![image](https://user-images.githubusercontent.com/18685116/183096777-1aee6c3b-8e17-4e6f-9dc7-2623ba859890.png)

Additionally, it would make sense to update the docs and inform users of how duplicate rows are actually handled:
![image](https://user-images.githubusercontent.com/18685116/183096964-7707f964-149a-4636-ba06-3ceb9465df20.png)

Small adjustment, but while we're at it we might as well make this code more legible:
![image](https://user-images.githubusercontent.com/18685116/183097204-9f29df47-b450-487d-9e6a-20114c783196.png)

**Comment by rymarinelli** [comment]
@barrettk I'm not sure if we want to remove the duplicated column. I think that could disrupt the ordering of the rest of the columns. It might be better to have the end user re-specify the ordering they want to use.

**Comment by barrettk** [comment]
@rymarinelli this is for duplicate rows, not columns. In this case we just want to remove the **printing** of the duplicate rows
