### ISSUE TITLE
Add submit_model(..., .overwrite) argument

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#544]
The proposed change is to add an `.overwrite` argument to `submit_model()` (similar to how `new_model()` and `copy_model_from()` have one) so that the user doesn't need to pass it through `.bbi_args`.

When we make this change, we should also update [this section](https://metrumresearchgroup.github.io/bbr/articles/getting-started.html#passing-arguments-to-bbi) of the "Getting Started" vignette.

**Comment by kyleam** [comment]
#547 pulls out the related commits from the unmerged bbr_stan_alpha branch.
