### ISSUE TITLE
Add description of eigenvalue_issues heuristic in model_summary() docs

### ISSUE THREAD

**Issue by timwaterhouse** [metrumresearchgroup/bbr#597]
`model_summary()` documentation currently lists details on other run heuristics but is missing `eigenvalue_issues`.

From bbi news: 
```Added eigenvalue_issues heuristic, triggered when any of the of the eigenvalues <= 0, or if NONMEM needs to force them to be positive. (#216)```

**Comment by seth127** [comment]
Yep, in looking into this, @timwaterhouse and I (and others) discussed this [here](https://github.com/metrumresearchgroup/bbi/pull/215#discussion_r618446356) and I even said

> The docs for ?model_summary would explain that this flag can mean a few different things and "the user should check...".

But then I guess I never did that. Oops.
