### ISSUE TITLE
Refactor current functions to use `nmrec`

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#599]
There are several current `bbr` functions that rely on raw string parsing of the control stream and would likely be more robust if they used the new `nmrec` package instead. Specifically, once the changes from https://github.com/metrumresearchgroup/nmrec/pull/5 are released (discussion on release begins [here](https://github.com/metrumresearchgroup/nmrec/pull/5#issuecomment-1613418533)).

Several examples:

* [x] `test_threads()`, notably [here](https://github.com/metrumresearchgroup/bbr/blob/main/R/test-threads.R#L351-L376)
* [x] `nm_table_files()`, specifically [here](https://github.com/metrumresearchgroup/bbr/blob/main/R/nm-tables.R#L90-L96)
* [x] `copy_control_stream()` (internal), specifically [here](https://github.com/metrumresearchgroup/bbr/blob/main/R/copy-model-from.R#L227-L232) (side note, it's not clear to me that [this line](https://github.com/metrumresearchgroup/bbr/blob/main/R/copy-model-from.R#L232) needs to be there...)
* [ ] `update_model_id()`, really [most of the function](https://github.com/metrumresearchgroup/bbr/blob/main/R/copy-model-helpers.R#L74-L97)
   skipped: see discussion starting at https://github.com/metrumresearchgroup/bbr/pull/605#issuecomment-1660822495

These don't need to be done all at once, and some may not be worth doing at all, but they were related enough to put them in the same issue. If anyone sees more cases like this in the code base, feel free to add them to this issue.

**Comment by kyleam** [comment]
> Specifically, once the changes from https://github.com/metrumresearchgroup/nmrec/pull/5 are released

This is probably for discussion outside of GitHub, but, in the case for bbr (at least for non-optional code), won't a bbr release that depends on nmrec need to wait for nmrec make it to MPN?

**Comment by kyleam** [comment]
And thanks for pulling together these examples.

**Comment by seth127** [comment]
> won't a bbr release that depends on nmrec need to wait for nmrec make it to MPN?

Hmmm, good thought there. Yes, let's discuss offline. I'm not sure that's a hard requirement, but probably is the smoothest path forward.

**Comment by kyleam** [comment]
I don't think there's anything in-flight here.  It probably makes sense to open a dedicated PR for anything else that comes up, but please reopen if I'm missing something.
