### ISSUE TITLE
bbr package

### ISSUE THREAD

**Issue by jeslo328** [metrumresearchgroup/bbr#601]
Hello
Im trying to install bbr package but i cant
devtools::install_github("metrumresearchgroup/bbr", ref = "main")

> devtools::install_github("metrumresearchgroup/bbr", ref = "main")
Downloading GitHub repo metrumresearchgroup/bbr@main
✔  checking for file ‘/SFS/scratch/lohydas/Rtmp/RtmpqEiub9/remotes7e561f9748d7/metrumresearchgroup-bbr-1fd58de/DESCRIPTION’ (641ms)
─  preparing ‘bbr’: (1.7s)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts (1.2s)
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘bbr_1.7.0.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
Installing package into ‘/SFS/user/ctc/lohydas/WORK/doravirine/renv/library/R-4.2/x86_64-pc-linux-gnu’
(as ‘lib’ is unspecified)
* installing *source* package ‘bbr’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
Execution halted
ERROR: lazy loading failed for package ‘bbr’
* removing ‘/SFS/user/ctc/lohydas/WORK/doravirine/renv/library/R-4.2/x86_64-pc-linux-gnu/bbr’
Warning message:
In i.p(...) :
  installation of package ‘/SFS/scratch/lohydas/Rtmp/RtmpqEiub9/file7e563341b018/bbr_1.7.0.tar.gz’ had non-zero exit status

> library(bbr)
Error in library(bbr) : there is no package called ‘bbr’

**Comment by kyleam** [comment]
From the output above, this is what sticks out:

> In file(filename, "r", encoding = encoding) :
> cannot open file 'renv/activate.R': No such file or directory

That suggests that your renv setup is in an invalid state, without an `renv/activate.R` file but with `source("renv/activate.R")` in your local `.Rprofile`.

If you want to use renv for the project (bbr doesn't require users manage their dependencies in any particular way), you could try this to fix the setup:

 * remove `source("renv/activate.R")` from your project's `.Rprofile` (it's also possible that that line is in another initialization file, but that'd be unusual)

 * call `renv::init(bare = TRUE)` from an R console for that project

 * `renv::install("devtools")` if it's not already in your project's renv library

 * `devtools::install_github("metrumresearchgroup/bbr", ref = "main")`

**Comment by kyleam** [comment]
@jeslo328 I think this is likely an issue with your renv setup, and I can't think of anything on bbr's end that would be responsible. So I'm going to close this, but please feel free to follow up with more details, and we'll try to help if we can.
