### ISSUE TITLE
bbi_init: clarify .nonmem_dir

### ISSUE THREAD

**Issue by kyleam** [metrumresearchgroup/bbr#607]
cc: @seth127 

The location of `.nonmem_dir` is a frequent source of confusion.  `bbi_init` (and `bbi init` underneath) expect to be pointed to a directory that has multiple installations.  Using Metworx as an example, `.nonmem_dir` should be `/opt/NONMEM`:

```
$ ls -1 /opt/NONMEM/
nm73gf
nm73gf_nmfe
nm74gf
nm74gf_nmfe
nm75
```

Underneath, each of those is a NONMEM installation:
```
$ ls -d /opt/NONMEM/nm75/run
/opt/NONMEM/nm75/run
```

Here's what the docs currently say:

https://github.com/metrumresearchgroup/bbr/blob/1fd58de8f4eddc8c9d2cc02c947e85b47a5aaf16/R/bbr.R#L326-L326

It'd be good to rephrase/extend that to make it clearer that `/opt/NONMEM` not `/opt/NONMEM/nm75` is the expected input.

**Comment by seth127** [comment]
@kyleam @barrettk we just had another external (to Metrum) user reach out with this confusion. Let's put this on the list to knock out before the next release too. Obviously it would be preferable to point them to the docs instead of pointing them to an open issue about how we intend to update the docs...

**Comment by barrettk** [comment]
@seth127 @kyleam I can take this on today/tomorrow if you guys want. Would like to take a look at the support ticket though just to get a better sense of how we can make the documentation as clear as possible.

**Comment by kyleam** [comment]
Great, thanks @barrettk.  

I don't know of a support ticket offhand.  (This came up a bit in gh-596, but there were several other things going on there, so I'm not sure that helps to look through.)   Perhaps @seth127 can point you to a support ticket or some other issue, but I think the main confusion boils down to thinking you should pass the NONMEM installation directory rather than the parent directory that contains that installation (which I think is understandable given bbi_init's description for `.nonmem_dir`).

Fwiw bbi's documentation is this "a directory in which to look for NonMem Installations"

https://github.com/metrumresearchgroup/bbi/blob/835953efed10fff2d7024ac1c3dd88949b268c05/cmd/init.go#L64
