### ISSUE TITLE
Update pkgr.yml to newest MPN for nmrec

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#628]
The new `inherit_param_estimates()` feature relies on `nmrec >= 0.3.0`, which we are currently installing from GitHub because it isn't on MPN yet. Once it is one MPN, we should update the snapshot in our `pkgr.yml` so that developers won't need this workaround. At the same time, we should update the comment to mention `nmrec` instead of just `mrgval`.

**Comment by kyleam** [comment]
Addressed with 9d91b5c1 (update MPN snapshot in pkgr, 2024-05-03).

https://github.com/metrumresearchgroup/bbr/blob/9d91b5c1fb55057d40b735571135d620946d0f09/pkgr.yml#L10-L12

> At the same time, we should update the comment to mention `nmrec` instead of just `mrgval`.

There's no longer a comment saying what dependencies come from MPN, but I think that's okay.  It's easy enough to drop the MPN repo and run `pkgr plan` to get an updated list of packages that come from MPN (currently nmrec and mrgmisc).

(mrgval deps were pruned in 53ec9422.)
