### ISSUE TITLE
Remove `mrgvalidate` and `mrgvalprep` from DESCRIPTION

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbr#629]
We are no longer using either of these, so we should remove them from `Suggests`.

I noticed that they were still there when filing #628

**Comment by kyleam** [comment]
Give the switch in validation approach, I think (didn't verify latest state) a good number of our packages have this (unsurpsingly).  We've got an internal ticket to clean up mrgval* related things across packages (275).  (Of course a cleanup just for bbr is fine, but seems worth mentioning in case whoever takes this on is up for doing a wider sweep.)
