### ISSUE TITLE
Bootstrap: revisit how we sample the input data

### ISSUE THREAD

**Issue by barrettk** [metrumresearchgroup/bbr#676]
Before we finalize the new bootstrap feature, I want to make sure we revisit the `resample_df` function, currently ported over from `mrgmsic` (along with 3 required helper functions).

`mrgmisc` files of interest:
 - https://github.com/metrumresearchgroup/mrgmisc/blob/main/R/resampling_functions.R
 - https://github.com/metrumresearchgroup/mrgmisc/blob/main/R/pad_left.R

As of making this issue, the core differences are:
 - A different "padding" mechanism (mostly because I didnt want to pull in the Rcpp method it used, but also because the new method looked nicer).
 - removed comments, a numeric check on a column (not sure why that was there), and doc changes (not all shown below)

Here is the file diff of those four functions (2 separate PNGs):
![image](https://github.com/metrumresearchgroup/bbr/assets/18685116/c72267fa-bc1e-4024-a9d8-783bec916c51)
![image](https://github.com/metrumresearchgroup/bbr/assets/18685116/dccaeaa3-bd93-41e0-8ab2-adb469b5607f)

**Comment by seth127** [comment]
This is being added in https://github.com/metrumresearchgroup/bbr/pull/671 specifically [here](https://github.com/metrumresearchgroup/bbr/blob/6b02c5973a7f9f36b0bd24d2a92a061972e584ce/R/bootstrap-model.R#L173-L174)

**Comment by seth127** [comment]
@michaelmcd18 is going to look into this. He's been doing most of the recent maintenance on `mrgmisc`.

**Comment by barrettk** [comment]
Addressed in https://github.com/metrumresearchgroup/bbr/pull/671

 - We opted to import this function from `mrgmisc` with no changes
