### ISSUE TITLE
Bootstrap: function adjustments needed

### ISSUE THREAD

**Issue by barrettk** [metrumresearchgroup/bbr#679]
Items with `+` by them have a note under the table.

|                             | needs work?   | blocker? |
|--------------------------- |------------- |-------- |
| **methods**                 |               |          |
| `as_summary_list`           | n          |          |
| `build_path_from_model`     | n ?         |          |
| `check_ext`                 | n ?           |          |
| `check_grd`                 | n ?       |         |
| `check_output_dir`          | n       |         |
| `check_up_to_date`          | **y?**  +  |  y        |
| `config_log_make_entry`     | n            |          |
| `copy_model_from`           | n  ?           |          |
| `cov_cor`                   | n ?         |       |
| `create_model_hook`         | n             |          |
| `get_based_on`              | n             |          |
| `get_config_path`           | n             |          |
| `get_data_path`             | n             |          |
| `get_model_ancestry`        | n             |          |
| `get_model_id`              | n             |          |
| `get_model_path`            | n             |          |
| `get_output_dir`            | n             |          |
| `get_yaml_path`             | n             |          |
| `model_diff`                | **n** - addressed     |     n     |
| `model_summaries`           |   n      |        |
| `model_summary`             | n     |         |
| `nm_file`                   | n       |        |
| `param_estimates`           | n         |         |
| `param_labels`              | n             |          |
| `print`                     | n           |          |
| `print_model_files`         | n             |          |
| `submit_model`              | n             |          |
| `submit_models`             | **y** +    | **y**        |
| `tags_diff`                 | n             |          |
| `tail_lst`                  | n        |          |
| `tail_output`               | n      |         |
| `wait_for_nonmem`           | n            |          |
|                             |               |          |
| **regular functions**       |               |          |
| `add_based_on`              | n             |          |
| `add_bbi_args`              | n             |          |
| `add_config`                | **y** +   | n        |
| `add_description`           | n             |          |
| `add_notes`                 | n             |          |
| `add_star`                  | n             |          |
| `add_summary`               | **y** +  |  n        |
| `add_tags`                  | n             |          |
| `add_tags_diff`             | n          |          |
| `apply_indices`             | n             |          |
| `bbi_current_release`       | n             |          |
| `bbi_help`                  | n             |          |
| `bbi_init`                  | n             |          |
| `bbi_version`               | n             |          |
| `block`                     | n             |          |
| `check_cor_threshold`       | n             |          |
| `check_file`                | n             |          |
| `check_nonmem_finished`     | n       |         |
| `check_nonmem_table_output` | n             |          |
| `check_run_times`           | **n**        | n        |
| `check_status_code`         | n             |          |
| `check_yaml_in_sync`        | n             |          |
| `collapse_to_string`        | n             |          |
| `config_log`                | **y** +   | n        |
| `ctl_ext`                   | n             |          |
| `delete_models`             | n             |          |
| `format_cmd_args`           | n             |          |
| `get_omega`                 | n?       |         |
| `get_sigma`                 | n?       |         |
| `get_theta`                 | n?       |         |
| `mod_ext`                   | n             |          |
| `modify_model_field`        | n             |          |
| `new_ext`                   | n             |          |
| `new_model`                 | n             |          |
| `nm_data`                   | n             |          |
| `nm_grd`                    | n      |       |
| `nm_join`                   | n      |         |
| `nm_par_tab`                | n      |      |
| `nm_tab`                    | n      |       |
| `nm_table_files`            | n      |      |
| `nm_tables`                 | n        |         |
| `open_model_file`           | n        |          |
| `param_estimates_batch`     | n        | n       |
| `param_estimates_compare`   | n             |          |
| `plot_ext`                  | n?            |          |
| `plot_grd`                  | n?           |          |
| `plot_nonmem_table_df`      | n?            |          |
| `print_bbi_args`            | n             |          |
| `read_bbi_path`             | n             |          |
| `read_model`                | n             |          |
| `reconcile_yaml`            | n             |          |
| `remove_based_on`           | n             |          |
| `remove_notes`              | n             |          |
| `remove_star`               | n             |          |
| `remove_tags`               | n             |          |
| `replace_all_based_on`      | n             |          |
| `replace_all_bbi_args`      | n             |          |
| `replace_all_notes`         | n             |          |
| `replace_all_tags`          | n             |          |
| `replace_description`       | n             |          |
| `replace_model_field`       | n             |          |
| `replace_note`              | n             |          |
| `replace_tag`               | n             |          |
| `run_log`                   | n   +  |         |
| `summary_log`               | **y**  | n        |
| `suppressSpecificWarning`   | n             |          |
| `test_threads`              | **n?**  +      |      n    |
| `update_model_id`           | n             |          |
| `use_bbi`                   | n             |          |
| `yaml_ext`                  | n             |          |

* **`check_up_to_date()`**: This has been implemented for both `nmsim` and `nmboot` models, though the `nmboot` method may require a closer look.
 * **`submit_models()`**: `submit_model` is used for bootstrap runs. I dont think we need to support submitting multiple bootstrap runs at the same time, as this seems like an edge case. We include `submit_model` examples in the docs too, so I dont imagine any users would be submitting multiple bootstraps at once within the same call.
 * **`config_log()`**: `run_log()` works by default with no modifications. However `config_log` automatically filters out models that dont have a `bbi_config.json`, which a `bbi_nmboot_model` object will never have. A notable refactor will be required here, to instead pull from spec files for `bbi_nmboot_model` and `bbi_nmsim_model` objects.
 * **`summary_log()`**: Needs handling. Will have to rely on results from `summarize_bootstrap_run`.
 * **`add_config()`** & **`add_summary()`**: need handling for a config columns and `bbi_summary` columns.
 * **`test_threads()`**: Cannot be done currently. `nmboot` models cant be copied via `copy_model_from`, and simulations were not intended to be created that way. We would need a new `copy_bootstrap_from` function or `nmboot` method for `copy_model_from` to implement.
 * **`check_run_times()`**: After looking into it, this function cannot support simulations or bootstrap runs, as it requires `model_summary()` information (specifically run details). `bbi` cannot retrieve this information for simulations, and im not sure it makes sense to implement an `nmboot` method.

**Comment by seth127** [comment]
I also wanted to put `inherit_param_estimates()` and `initial_estimates()` on this list. I _think_ this should be as simple as adding an S3 dispatch that just dispatches through to `bbi_nonmem_model`, but I haven't looked into too deeply.

<img width="621" alt="Screenshot 2024-05-09 at 1 30 02 PM" src="https://github.com/metrumresearchgroup/bbr/assets/7806083/b7ce6853-a2a0-408d-b675-d23de99f9cdd">

**Comment by seth127** [comment]
Whenever we come back to this, I also wanted to throw out the idea of just keeping `bbi_nonmem_model` as a parent class to `bbi_nmboot_model`. To be clear, currently we have this:

```r
class(boot_run)
[1] "bbi_nmboot_model" "bbi_base_model"   "bbi_model"        "list"  
```

I'm proposing this:

```r
class(boot_run)
[1] "bbi_nmboot_model" "bbi_nonmem_model" "bbi_base_model"   "bbi_model"        "list"  
```

We would need to think through the repercussions of this more, but naively I think it might be an easy and elegant solution for some number of the functions mentioned in this issue. For example, open the fold below to see my quick testing from hacking the class manually.

<details><summary>manually adding bbi_nonmem_model class</summary>

Currently fails (as of `1.10.0.8003`)

```r
> class(boot_run)
[1] "bbi_nmboot_model" "bbi_base_model"   "bbi_model"        "list"            
> model_diff(boot_run)
Error in UseMethod("model_diff") : 
  no applicable method for 'model_diff' applied to an object of class "c('bbi_nmboot_model', 'bbi_base_model', 'bbi_model', 'list')"
> inherit_param_estimates(boot_run)
Error in check_model_object(.mod, "bbi_nonmem_model") :
Must pass a model object with one of the following classes: `bbi_nonmem_model`
Got object of class: `bbi_nmboot_model, bbi_base_model, bbi_model, list`
```

Works if I manually add the class

```r
> class(boot_run)
[1] "bbi_nmboot_model" "bbi_base_model"   "bbi_model"        "list"            
> class(boot_run) <- c("bbi_nonmem_model", class(boot_run))
> class(boot_run)
[1] "bbi_nonmem_model" "bbi_nmboot_model" "bbi_base_model"   "bbi_model"        "list"            
> model_diff(boot_run)
< 106-boot                                                               > 106                                                                  
@@ 1,3 @@                                                                @@ 1,3 @@                                                              
< $PROBLEM Bootstrap run of model 106                                    > $PROBLEM From bbr: see 106.yaml for details                          
                                                                                                                                                
  $INPUT C NUM ID TIME SEQ CMT EVID AMT DV AGE WT HT EGFR ALB BMI SEX A    $INPUT C NUM ID TIME SEQ CMT EVID AMT DV AGE WT HT EGFR ALB BMI SEX A
  AG                                                                       AG                                                                   
@@ 52,2 @@                                                               @@ 52,5 @@                                                             
                                                                                                                                                
  $EST MAXEVAL=9999 METHOD=1 INTER SIGL=6 NSIG=3 PRINT=1 MSFO=./106.msf    $EST MAXEVAL=9999 METHOD=1 INTER SIGL=6 NSIG=3 PRINT=1 MSFO=./106.msf
                                                                                                                                                
~                                                                        > $COV PRINT=E                                                         
~                                                                        > $TABLE NUM CL V2 Q V3 KA ETAS(1:LAST) IPRED NPDE CWRES NOPRINT ONEHEA
~                                                                        : DER FILE=106.tab                                                     
~                                                                        > $TABLE NUM CL V2 Q V3 KA ETAS(1:LAST) NOAPPEND NOPRINT ONEHEADER FILE
~                                                                        : =106par.tab                                                          
> boot_run <- inherit_param_estimates(boot_run)
                                                                                                                                                                                    
> model_diff(boot_run)
< 106-boot                                                               > 106                                                                  
@@ 1,3 @@                                                                @@ 1,3 @@                                                              
< $PROBLEM Bootstrap run of model 106                                    > $PROBLEM From bbr: see 106.yaml for details                          
                                                                                                                                                
  $INPUT C NUM ID TIME SEQ CMT EVID AMT DV AGE WT HT EGFR ALB BMI SEX A    $INPUT C NUM ID TIME SEQ CMT EVID AMT DV AGE WT HT EGFR ALB BMI SEX A
  AG                                                                       AG                                                                   
@@ 34,20 @@                                                              @@ 34,23 @@                                                            
                                                                                                                                                
  $THETA  ; log values                                                     $THETA  ; log values                                                 
< (0.443)   ;  1 KA (1/hr) - 1.5                                         > (0.5)   ;  1 KA (1/hr) - 1.5                                         
< (4.12)   ;  2 V2 (L) - 60                                              > (3.5)   ;  2 V2 (L) - 60                                             
< (1.17)     ;  3 CL (L/hr) - 3.5                                        > (1)     ;  3 CL (L/hr) - 3.5                                         
< (4.21)     ;  4 V3 (L) - 70                                            > (4)     ;  4 V3 (L) - 70                                             
< (1.28)     ;  5 Q  (L/hr) - 4                                          > (2)     ;  5 Q  (L/hr) - 4                                           
< (0.485)     ;  6 CLEGFR~CL ()                                          > (1)     ;  6 CLEGFR~CL ()                                            
< (-0.0378)     ;  7 AGE~CL ()                                           > (1)     ;  7 AGE~CL ()                                               
< (0.419)   ;  8 ALB~CL ()                                               > (0.5)   ;  8 ALB~CL ()                                               
                                                                                                                                                
  $OMEGA BLOCK(3)                                                          $OMEGA BLOCK(3)                                                      
< 0.219   ;ETA(KA)                                                       > 0.2   ;ETA(KA)                                                       
< 0.0668 0.0824   ;ETA(V2)                                               > 0.01 0.2   ;ETA(V2)                                                  
< 0.121 0.0704 0.114   ;ETA(CL)                                          > 0.01 0.01 0.2   ;ETA(CL)                                             
                                                                                                                                                
  $SIGMA                                                                   $SIGMA                                                               
< 0.0399     ; 1 pro error                                               > 0.05     ; 1 pro error                                               
                                                                                                                                                
  $EST MAXEVAL=9999 METHOD=1 INTER SIGL=6 NSIG=3 PRINT=1 MSFO=./106.msf    $EST MAXEVAL=9999 METHOD=1 INTER SIGL=6 NSIG=3 PRINT=1 MSFO=./106.msf
                                                                                                                                                
~                                                                        > $COV PRINT=E                                                         
~                                                                        > $TABLE NUM CL V2 Q V3 KA ETAS(1:LAST) IPRED NPDE CWRES NOPRINT ONEHEA
~                                                                        : DER FILE=106.tab                                                     
~                                                                        > $TABLE NUM CL V2 Q V3 KA ETAS(1:LAST) NOAPPEND NOPRINT ONEHEADER FILE
~                                                                        : =106par.tab 
```

</details>

**Comment by barrettk** [comment]
>We would need to think through the repercussions of this more, but naively I think it might be an easy and elegant solution for some number of the functions mentioned in this issue. 

I think this would work very well for the new `nmsim` model type, but yeah there are definitely a number of cases we'd need to have additional handling for `nmboot` model objects, such as pulling in gradients, tables, `build_path_from_model`, etc. that wont work either because the directory is different, or because the actual model file itself (`.ctl`) doesnt actually get submitted/generate submission files.

**Thought:** could it make sense to do this for the `nmsim` model type, but _not_ `nmboot` model objects?

**Comment by barrettk** [comment]
`check_up_to_date` for bootstrap runs was implemented in https://github.com/metrumresearchgroup/bbr/pull/687/commits/8e6134aa4331a42100eb569162c47d56b0b45e70 - @seth127 @kylebaron you guys may specifically want to take a look at this handling to make sure its implemented the way we want it to be. 
 - Something Seth noted though: we have to return a final object of `length 2` with names `model` and `data`. So if we want to include additional checks, they either have to be grouped into `data` or `model`, or be isolated from the returned vector
