### ISSUE TITLE
WK files created by bbr - delete by default?

### ISSUE THREAD

**Issue by jacobleander** [metrumresearchgroup/bbr#686]
When running NONMEM in parallel on 'sge' using bbr, there is a bunch of WK_ files created that is not deleted. They are all empty. Maybe the default can be to delete these WK files after NONMEM run is completed?

**Comment by kyleam** [comment]
@jacobleander Thanks for filing an issue.

What `bbi` version are you using?  The latest bbi (version 3.3.0) should take care of removing these (metrumresearchgroup/bbi#306).

**Comment by jacobleander** [comment]
Thanks for quick response. I am using 3.2.3 (I have not installed it locally in my project activity). I guess then I use the default version that is installed on my disk (using blueprint 22.09).

**Comment by kyleam** [comment]
Hmm, the bbi version that ships with 22.09 is 3.1.1:

```
$ /usr/local/bin/bbi version
v3.1.1
$ echo $METWORX_VERSION
22-09.00.04
```

Perhaps you've got another installed somewhere on your `PATH`.  `which bbi` would let you know what's taking precedence in your shell.

If you'd like to try out the latest bbi, you could install under a specific project by invoking this from the R console:

```
# from top-level of project
bbr::use_bbi("bin/bbi")
```

And then point the `bbr.bbi_exe_path` option to it (typically done in the project's `.Rprofile`):

```
options('bbr.bbi_exe_path' = file.path(getwd(), "bin", "bbi"))
```

**Comment by kyleam** [comment]
By the way, the upcoming Metworx blueprint will ship with the latest bbi.

**Comment by kyleam** [comment]
@jacobleander Yes, look like it.  If you want to update the `bbi` installed at that path, you can call `bbr::use_bbi()` without any arguments.  It defaults to `bbr.bbi_exe_path` if it's set.

**Comment by kyleam** [comment]
@jacobleander I'll close this issue, as it should be resolved by the latest bbi, but if you run into any problems once you update, please let us know.  Thanks.
